name: DungeonPoint
version: '${version}'
main: com.github.bryanser.dungeonpoint.Main
depend: [BrAPI,CustomGo]
authors: [Bryan33]
website: https://github.com/BryanSer
commands:
  DungeonPoint:
    aliases: [dp,dunp,dpoint]
    usage: |
      /<command> clear [x-x] (player) >> 标记玩家通过某个难度,如果不输入玩家名则默认是自己
      /<command> point [分数] [key] (player) >> 为目标玩家所在的副本添加或减少分数,key是用于去重的
        key填写_则可以忽略去重
      /<command> max [分数] [x-x] (player) >> 为目标玩家所在的副本设定通关目标,可以随时更新